name: Notify Discord on Push
on:
  push:
    branches: [ main ]

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Build JSON payload
        run: |
          cat <<EOF > payload.json
          {
            "username": "GitHub Bot",
            "embeds": [
              {
                "title": "🔄 Push to ${{ github.repository }}",
                "description": "By **${{ github.actor }}**\nSee changes: <${{ github.event.compare }}>",
                "color": 15258703,
                "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              }
            ]
          }
          EOF

      - name: Send to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -v -X POST "${WEBHOOK}" \
            -H "Content-Type: application/json" \
            -d @payload.json
