name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Build payload
        id: build
        run: |
          PAYLOAD=$(
            jq -n \
              --arg user "${{ github.actor }}" \
              --arg repo "${{ github.repository }}" \
              --arg url "${{ github.event.compare }}" \
              '{
                "username": "GitHub Bot",
                "embeds": [
                  {
                    "title": "🔄 Push to \($repo)",
                    "description": "By **\($user)**\nSee changes: <\($url)>",
                    "color": 15258703,
                    "timestamp": "\(now)"
                  }
                ]
              }'
          )
          echo "::set-output name=payload::$PAYLOAD"

      - name: Send to Discord
        run: |
          curl -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "${{ steps.build.outputs.payload }}"
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
